### PR TITLE
Changes to make files

### PR DESCRIPTION
**Pull request by Bhlowe**
Some edits required to build and run tests.

### CODE REVIEW

**Comment by Bhlowe** [comment]
A sample build script and Dockerfile for building and testing

**Review by rguadagno — APPROVED** [review]
looks good!

**Comment by Bhlowe** [comment]
Hi Richard,

I created a quick demo of of what a smart stack trace might look like.. in
json format.

https://github.com/Bhlowe/smartstack/invitations

I've seen a number of web-based debuggers.. so a simple UI might be as easy
as looking for some open source options..
This one isn't open source, but you get the idea..
https://www.onlinegdb.com/

- Brad

**Comment by rguadagno** [comment]
Hi Brad,
    I have pushed some code up to the repo - output is just raw and it is
not complete... I am now working on getting fields for an object which has
a recursive nature so taking care of that. I am working under the
assumption that the target code of the user would not be compiled with -g.
Even without the debug info I can get local variables - but would have to
try each  type -  but if user viewed with their java src ( which they would
else what is the point) we can map up the variables to names - I tried this
already and the bytecode is created in order of how they are declared.

So far no show stoppers or problems.  I will push in more code probably
tomorrow - we can regroup then.

-Richard.

**Comment by Bhlowe** [comment]
Looks good. I wasn't able to compile -- complaining about optional. Wasn't
sure if that was boost or C++17 and didn't track it down. I'm building on
ubuntu 16...

Glad you made some progress.. I took some screenshots of the overops and
made some notes about what they do when there is too much data to fit into
a stack trace -- basically they limit the data to 300 or so bytes per
structure.. and I assume also limit the number of fields, variables, etc.

At some point we should get a way to write down ideas and brainstorm the
product..
One thing I saw that might help or hurt is Java Mission Control
<http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html>
is now open source <http://hg.openjdk.java.net/jmc>.. which might be a neat
way to get smartstack into a nice GUI quickly. Especially nice if we can do
it as a plug-in without a lot of fuss... Will look into JMC more. But first
look I didn't see any c++ agent code.

- Brad

**Comment by rguadagno** [comment]
Hi Brad,

   I've just pushed more code: removed std::optional ( was actually causing
a bug I spent some time on - haha) and added recursive type drill down.  I
have attached the java code I was using to run against.

The code is raw and limited but shows that this is all possible.
Can I give you call today at 10:30 AM (PT)  ?

-Richard.

**Comment by Bhlowe** [comment]
That fixed the compile problem -- commented one // include <optional> in
Variable.h
Lets talk at 10:30!
- Brad

**Comment by rguadagno** [comment]
hey - was just thinking - prob not too hard for me to put together a demo
tool : agent + server/monitor + web gui  ... going to think about the
technical issues - goal is to make it connect the dots - lets see...

**Pull request merged**
